version: "2"
services:
  application:
    image: maven:3.5.0-jdk-8-alpine
    container_name: cloud_values
    working_dir: /application
    volumes:
      - ./application:/application
    command: sh -c "mvn clean package"